library(readr)
setwd("E:/Show work/R-system")
df <- read_csv("data/processed/jobs_clean.csv", show_col_types=FALSE)
cat("行数:", nrow(df), "\n")
cat("列名:", paste(names(df), collapse=", "), "\n")
cat("\n城市示例:\n")
print(head(df$city, 10))
cat("\n薪资示例:\n")
print(head(df$salary, 10))
cat("\nsalary_avg示例:\n")
print(head(df$salary_avg, 10))
cat("\n数据来源:\n")
print(table(df$source))
cat("\n关键词分布:\n")
print(table(df$keyword))
